### ISSUE TITLE
Typo in Weight index for slide Perceptron in detail

### ISSUE THREAD

**Issue by woidda** [habernal/deep-learning-for-nlp-lectures#1]
If I am not wrong you have got an error in the index on the "Perceptron in detail" slide.
The index must be w_2 here instead of [w_1](https://github.com/habernal/deep-learning-for-nlp-lectures/blob/main/latex/lecture01/dl4nlp2021-lecture01.tex#L731).

I am not sure if a pull request or issue is better so I picked the later.

P.S. Thanks for the great lecture. Nice to see those topics in a rather easy to understand format.

**Comment by habernal** [comment]
Nice catch, thanks! (will fix it)

Both bug reports and PRs are much appreciated, thank you for contributing!
